version : 1
disable_existing_loggers : False
formatters :
    simple :
        format: "%(asctime)s [%(name)s] [%(levelname)s] line:%(lineno)d: %(message)s"
        datefmt: '%Y-%m-%d %A %H:%M:%S'

handlers :
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ./mytools/logs/wtools.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ./mytools/logs/error.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

loggers :
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root :
    level: DEBUG
    handlers: [console, info_file_handler,error_file_handler]